import logging
import re
from typing import Any, Dict

# Assuming vishustra_core.nodes.base_node exists at this path
from vishustra_core.nodes.base_node import BaseNode

logger = logging.getLogger(__name__)

class MarkdownParserNode(BaseNode):
    """
    A Vishustra node that parses Markdown text and transforms it into
    a simplified HTML representation.
    
    This node is designed to process text inputs, typically generated by LLMs,
    and convert common Markdown elements like headings, bold, italic, and lists
    into corresponding HTML tags.
    """

    @property
    def node_name(self) -> str:
        """Returns the name of the node."""
        return "MarkdownParserNode"

    def process(self, data: Any, context: Dict[str, Any]) -> Any:
        """
        Processes the input data, converting Markdown syntax into HTML.

        Supports a subset of Markdown:
        - Headings (#, ##, ###)
        - Bold (**, __)
        - Italic (*, _)
        - Unordered lists (-)
        - Blockquotes (>)
        - Code blocks (```)

        Args:
            data (Any): The input data, expected to be a string containing Markdown.
            context (Dict[str, Any]): A dictionary containing contextual information
                                       for the current processing flow.

        Returns:
            Any: A string containing the HTML representation of the input Markdown.

        Raises:
            TypeError: If the input `data` is not a string.
        """
        if not isinstance(data, str):
            error_msg = f"MarkdownParserNode received unsupported data type: {type(data)}. Expected a string."
            logger.error(error_msg, extra={"node_name": self.node_name})
            raise TypeError(error_msg)

        logger.debug(f"MarkdownParserNode received data for processing. Context: {context}",
                     extra={"node_name": self.node_name})

        parsed_html = []
        lines = data.split('\n')
        in_code_block = False
        in_list = False

        for line_num, line in enumerate(lines):
            stripped_line = line.strip()

            # Handle code blocks
            if stripped_line.startswith("```"):
                if not in_code_block:
                    parsed_html.append("<pre><code>")
                    logger.debug(f"Detected start of code block at line {line_num + 1}",
                                 extra={"node_name": self.node_name})
                else:
                    parsed_html.append("</code></pre>")
                    logger.debug(f"Detected end of code block at line {line_num + 1}",
                                 extra={"node_name": self.node_name})
                in_code_block = not in_code_block
                continue
            
            if in_code_block:
                parsed_html.append(line)
                continue

            # Handle headings
            if stripped_line.startswith('### '):
                parsed_html.append(f"<h3>{stripped_line[4:].strip()}</h3>")
                logger.debug(f"Parsed H3 heading at line {line_num + 1}",
                             extra={"node_name": self.node_name})
            elif stripped_line.startswith('## '):
                parsed_html.append(f"<h2>{stripped_line[3:].strip()}</h2>")
                logger.debug(f"Parsed H2 heading at line {line_num + 1}",
                             extra={"node_name": self.node_name})
            elif stripped_line.startswith('# '):
                parsed_html.append(f"<h1>{stripped_line[2:].strip()}</h1>")
                logger.debug(f"Parsed H1 heading at line {line_num + 1}",
                             extra={"node_name": self.node_name})
            # Handle blockquotes
            elif stripped_line.startswith('> '):
                # Simple blockquote handling, may need more robust for multi-line
                parsed_html.append(f"<blockquote>{stripped_line[2:].strip()}</blockquote>")
                logger.debug(f"Parsed blockquote at line {line_num + 1}",
                             extra={"node_name": self.node_name})
            # Handle unordered lists
            elif stripped_line.startswith('- '):
                if not in_list:
                    parsed_html.append("<ul>")
                    in_list = True
                    logger.debug(f"Detected start of unordered list at line {line_num + 1}",
                                 extra={"node_name": self.node_name})
                parsed_html.append(f"<li>{stripped_line[2:].strip()}</li>")
            else:
                if in_list:
                    parsed_html.append("</ul>")
                    in_list = False
                    logger.debug(f"Detected end of unordered list at line {line_num + 1}",
                                 extra={"node_name": self.node_name})

                # Apply inline formatting (bold, italic)
                processed_line = line
                processed_line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', processed_line)  # **bold**
                processed_line = re.sub(r'__(.*?)__', r'<b>\1</b>', processed_line)   # __bold__
                processed_line = re.sub(r'\*(.*?)\*', r'<i>\1</i>', processed_line)    # *italic*
                processed_line = re.sub(r'_(.*?)_', r'<i>\1</i>', processed_line)     # _italic_

                if processed_line.strip(): # Only add if not an empty line after processing
                    # Convert newlines not within blocks to <br/> for simpler paragraph handling
                    # This is a simplification; a full parser would wrap paragraphs in <p> tags
                    parsed_html.append(processed_line.strip() + "<br/>")

        if in_list: # Close list if markdown ends while in list
            parsed_html.append("</ul>")
            logger.debug("Closed unordered list at end of document",
                         extra={"node_name": self.node_name})

        result_html = "\n".join(parsed_html)
        logger.info(f"Successfully parsed Markdown to HTML. Original length: {len(data)}, "
                    f"Resulting HTML length: {len(result_html)}",
                    extra={"node_name": self.node_name})
        
        return result_html