import logging
import re
from typing import Any, Dict

from vishustra_core.nodes.base_node import BaseNode

logger = logging.getLogger(__name__)

class TextSummarizerNode(BaseNode):
    """
    A Vishustra processing node that performs text summarization.

    This node expects a string as input data and produces a summarized
    version of the text. The summarization here is a basic extractive
    method, taking the first N sentences. In a production environment,
    this would integrate with a sophisticated summarization model or API.
    """

    def __init__(self, default_max_sentences: int = 3):
        """
        Initializes the TextSummarizerNode with a default number of sentences
        to use for summarization.

        Args:
            default_max_sentences (int): The default number of sentences
                                         to extract for the summary if not
                                         explicitly provided in the process context.
                                         Must be a positive integer.
        Raises:
            ValueError: If `default_max_sentences` is not a positive integer.
        """
        if not isinstance(default_max_sentences, int) or default_max_sentences <= 0:
            raise ValueError("default_max_sentences must be a positive integer.")
        self._default_max_sentences = default_max_sentences
        logger.debug(f"TextSummarizerNode initialized with default_max_sentences: {default_max_sentences}")

    @property
    def node_name(self) -> str:
        """Returns the descriptive name of this node."""
        return "TextSummarizer"

    def process(self, data: Any, context: Dict[str, Any]) -> str:
        """
        Processes the input data, extracting a summary from the text.

        The summary is generated by taking the first `N` sentences of the
        input text. The number `N` can be specified in the `context`
        dictionary via the key 'max_sentences_to_summarize'; otherwise,
        the `default_max_sentences` set during initialization is used.

        Args:
            data (Any): The input data, expected to be a string containing
                        the text to be summarized.
            context (Dict[str, Any]): A dictionary providing additional
                                       parameters for the processing.
                                       Key 'max_sentences_to_summarize' (int)
                                       can override the default number of
                                       sentences for the summary.

        Returns:
            str: The summarized text. If the input is empty or contains no
                 discernible sentences, an empty string is returned.

        Raises:
            TypeError: If the input `data` is not a string.
        """
        logger.info(f"[{self.node_name}] Processing data for summarization.")

        if not isinstance(data, str):
            logger.error(f"[{self.node_name}] Invalid input type. Expected 'str', but received '{type(data).__name__}'.")
            raise TypeError(f"TextSummarizerNode expects string input, but received {type(data).__name__}.")

        stripped_data = data.strip()
        if not stripped_data:
            logger.warning(f"[{self.node_name}] Received empty or whitespace-only string. Returning empty string.")
            return ""

        max_sentences = context.get('max_sentences_to_summarize', self._default_max_sentences)

        if not isinstance(max_sentences, int) or max_sentences <= 0:
            logger.warning(
                f"[{self.node_name}] Invalid 'max_sentences_to_summarize' in context ('{max_sentences}', type: {type(max_sentences).__name__}). "
                f"Expected a positive integer. Falling back to default: {self._default_max_sentences} sentences."
            )
            max_sentences = self._default_max_sentences

        logger.debug(f"[{self.node_name}] Attempting to summarize text using the first {max_sentences} sentences.")

        # A basic sentence tokenizer; in a real-world application,
        # a more sophisticated NLP library (e.g., NLTK, spaCy) would be used.
        # This regex splits by common sentence-ending punctuation followed by whitespace,
        # but attempts to avoid splitting on decimals or abbreviations.
        sentence_splitter = re.compile(r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?|\!)\s+')
        sentences_raw = sentence_splitter.split(stripped_data)
        
        # Filter out empty strings that might result from splitting
        sentences = [s.strip() for s in sentences_raw if s.strip()]

        if not sentences:
            logger.debug(f"[{self.node_name}] No discernible sentences found in the input. Returning original (potentially empty) text.")
            return stripped_data

        summary_sentences = sentences[:max_sentences]
        summary = " ".join(summary_sentences)

        # Ensure the summary ends with appropriate punctuation if the last sentence
        # in the selection didn't naturally end with one and it's not empty.
        if summary and not re.search(r'[.!?]$', summary):
            summary += "." # Add a period for completeness

        logger.info(f"[{self.node_name}] Successfully summarized text. Original length: {len(stripped_data)}, Summary length: {len(summary)}.")
        logger.debug(f"[{self.node_name}] Summary result (first 100 chars): '{summary[:100]}{'...' if len(summary) > 100 else ''}'")

        return summary

