import logging
import re
from typing import Any, Dict

# Assuming BaseNode is located at vishustra_core/nodes/base_node.py
from vishustra_core.nodes.base_node import BaseNode

logger = logging.getLogger(__name__)

class TextSummarizerNode(BaseNode):
    """
    A processing node designed to simulate text summarization.

    This node accepts a string as input and generates a simulated summary
    by extracting either the first N words or the first M sentences.
    This serves as a placeholder for integration with actual LLM-based
    summarization services within the Vishustra framework.
    """

    @property
    def node_name(self) -> str:
        """Returns the programmatic name of this node."""
        return "TextSummarizer"

    def process(self, data: Any, context: Dict[str, Any]) -> str:
        """
        Simulates the summarization of input text based on configurable parameters.

        It expects `data` to be a string containing the full text to be summarized.
        The `context` dictionary can optionally include:
        - `summary_max_sentences` (int): If provided, the summary will be generated
          by taking up to this number of initial sentences. This parameter takes
          precedence over `summary_max_words`. Defaults to 3 if neither
          `summary_max_sentences` nor `summary_max_words` is specified.
        - `summary_max_words` (int): If `summary_max_sentences` is not used, the
          summary will be generated by taking up to this number of initial words.
          Defaults to 50 if `summary_max_sentences` is not provided.

        Args:
            data (Any): The input data, expected to be a string.
            context (Dict[str, Any]): A dictionary providing runtime configuration,
                                      such as summary length parameters.

        Returns:
            str: A string representing the simulated summary of the input text.

        Raises:
            TypeError: If the input `data` is not a string.
            ValueError: If `summary_max_words` or `summary_max_sentences` in the
                        `context` are not positive integers.
        """
        if not isinstance(data, str):
            logger.error(
                f"[{self.node_name}] Invalid input type. Expected string, got {type(data).__name__}."
            )
            raise TypeError(
                f"TextSummarizerNode expects 'data' to be a string for summarization, "
                f"but received {type(data).__name__}."
            )

        text_to_summarize: str = data.strip()

        if not text_to_summarize:
            logger.info(f"[{self.node_name}] Received an empty string, returning an empty summary.")
            return ""

        logger.debug(
            f"[{self.node_name}] Initiating summarization for text (length: {len(text_to_summarize)} characters)."
        )

        max_sentences = context.get("summary_max_sentences")
        max_words = context.get("summary_max_words", 50) # Default word count if sentences not specified

        # Validate context parameters
        if max_sentences is not None and (not isinstance(max_sentences, int) or max_sentences <= 0):
            raise ValueError(
                f"[{self.node_name}] Context parameter 'summary_max_sentences' must be a positive integer, "
                f"but received: {max_sentences} ({type(max_sentences).__name__})."
            )
        if max_words is not None and (not isinstance(max_words, int) or max_words <= 0):
            raise ValueError(
                f"[{self.node_name}] Context parameter 'summary_max_words' must be a positive integer, "
                f"but received: {max_words} ({type(max_words).__name__})."
            )

        summary_parts = []
        is_truncated = False

        if max_sentences is not None:
            # A more robust regex for sentence splitting to avoid splitting on abbreviations
            # This regex splits on periods, question marks, or exclamation points followed by whitespace,
            # but not on periods that are part of common abbreviations (e.g., Mr., Dr., etc.)
            sentences = re.split(r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?|\!)\s', text_to_summarize)
            summary_parts = sentences[:max_sentences]
            if len(sentences) > max_sentences:
                is_truncated = True
            logger.debug(f"[{self.node_name}] Simulating summary by first {max_sentences} sentences.")
        else:
            words = text_to_summarize.split()
            summary_parts = words[:max_words]
            if len(words) > max_words:
                is_truncated = True
            logger.debug(f"[{self.node_name}] Simulating summary by first {max_words} words.")

        simulated_summary = " ".join(summary_parts).strip()

        # Add ellipsis if the original text was longer than the summary length
        if is_truncated and not simulated_summary.endswith(('.', '?', '!')):
            simulated_summary += "..."

        logger.info(
            f"[{self.node_name}] Simulated summary generated (length: {len(simulated_summary)} characters)."
        )
        return simulated_summary