import asyncio
import json
import logging
from typing import List, Dict, Any, Optional, Union
from pydantic import BaseModel, Field, ValidationError

# Assume these core components are available from the Vishustra framework.
# For standalone clarity, minimal definitions are provided if external modules are not directly importable here.

# --- Vishustra Core Interfaces (Simplified for context) ---
class ChatMessage(BaseModel):
    """Represents a single message in a chat conversation within Vishustra."""
    role: str = Field(..., description="The role of the message sender (e.g., 'user', 'assistant', 'system').")
    content: str = Field(..., description="The textual content of the message.")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(None, description="Optional list of tool calls made by the assistant.")
    # Additional fields like 'name' for tool message, 'function_call', etc., could be added.

class ChatCompletionResponse(BaseModel):
    """Encapsulates a response from an LLM chat completion API call."""
    message: ChatMessage = Field(..., description="The primary message generated by the LLM.")
    model_name: Optional[str] = Field(None, description="The name of the LLM model that generated the response.")
    prompt_tokens: Optional[int] = Field(None, description="Number of tokens in the input prompt.")
    completion_tokens: Optional[int] = Field(None, description="Number of tokens in the generated completion.")
    # Further details like 'finish_reason', 'usage_metadata' could be included.

class LLMProvider:
    """
    Abstract interface for an LLM provider within Vishustra.
    Concrete implementations would connect to specific LLM APIs (e.g., OpenAI, Anthropic).
    """
    async def async_chat_complete(self, messages: List[ChatMessage], **kwargs) -> ChatCompletionResponse:
        """
        Asynchronously completes a chat conversation given a list of messages.

        Args:
            messages: A list of `ChatMessage` objects representing the conversation history.
            **kwargs: Additional parameters to pass to the underlying LLM API (e.g., `model`, `temperature`, `max_tokens`).

        Returns:
            A `ChatCompletionResponse` object containing the LLM's reply and metadata.

        Raises:
            NotImplementedError: If the method is not implemented by a concrete provider.
            VishustraLLMError: Custom exception for LLM API-specific errors (not defined here for brevity).
        """
        raise NotImplementedError("This method must be implemented by a concrete LLMProvider.")

# Using Python's built-in logging module, typically configured globally in Vishustra.
logger = logging.getLogger(__name__)

# --- Vishustra Semantic Router Components ---

class RouteTarget(BaseModel):
    """
    Represents a potential route for an incoming query within the Vishustra framework.
    Each target should have a clear name and a descriptive purpose to aid the routing LLM.
    """
    name: str = Field(..., description="A unique programmatic identifier for the route (e.g., 'customer_support_chain', 'data_retrieval_tool').")
    description: str = Field(..., description="A clear, concise, and comprehensive description of what this route handles, its purpose, and what kind of queries it's designed for. This is crucial for the routing LLM's accuracy.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Arbitrary metadata associated with this route, such as a chain ID, a function pointer, or specific configuration parameters required by the downstream component.")

class RouteDecision(BaseModel):
    """
    The outcome of a Vishustra semantic routing operation, indicating the selected target
    and the confidence level.
    """
    selected_target: Optional[RouteTarget] = Field(None, description="The chosen route target, if a confident decision was made by the router.")
    confidence_score: float = Field(0.0, ge=0.0, le=1.0, description="The confidence score (0.0-1.0) assigned by the routing mechanism to the selected target.")
    reasoning: Optional[str] = Field(None, description="The LLM's explicit reasoning for the decision, providing transparency into the routing process.")
    all_scores: Dict[str, float] = Field(default_factory=dict, description="A dictionary of confidence scores for all potential targets, mapping target names to their scores, as estimated by the LLM.")
    fallback_triggered: bool = Field(False, description="True if a fallback mechanism was triggered, typically due to low confidence in any single route or an inability to parse the LLM's response.")

class SemanticRouter:
    """
    An advanced semantic router for Vishustra, designed to intelligently direct
    incoming user queries or internal requests to the most appropriate downstream
    chain, tool, or handler based on their semantic content.

    This router leverages a dedicated LLM to understand the intent behind a query
    and match it against a predefined set of `RouteTarget`s, each with a clear
    description of its purpose. It aims for high accuracy and provides transparency
    through confidence scores and explicit reasoning from the LLM.

    Attributes:
        llm_provider: An instance of `LLMProvider` to use for semantic classification.
        routes: A list of `RouteTarget` objects that define the possible routing destinations.
        default_fallback_route_name: The name of a `RouteTarget` to use if no confident
                                     match is found or if the LLM response is unparseable.
                                     This route MUST exist within the `routes` list.
        min_confidence_threshold: The minimum confidence score (0.0-1.0) required for a
                                  route to be considered selected. Below this, the fallback
                                  is typically triggered.
        llm_model_name: Optional; specifies a particular LLM model to use for routing
                        if the `llm_provider` supports multiple models.
        llm_temperature: The temperature setting for the routing LLM, controlling
                         the randomness of its responses (lower for more deterministic).
        system_prompt: Optional; allows overriding the default system instruction
                       given to the routing LLM.
    """

    def __init__(
        self,
        llm_provider: LLMProvider,
        routes: List[RouteTarget],
        default_fallback_route_name: Optional[str] = None,
        min_confidence_threshold: float = 0.7,
        llm_model_name: Optional[str] = None,
        llm_temperature: float = 0.1,
        system_prompt: Optional[str] = None
    ):
        if not routes:
            raise ValueError("SemanticRouter must be initialized with at least one RouteTarget.")

        self.llm_provider = llm_provider
        # Store routes in a dictionary for efficient lookup by name
        self.routes: Dict[str, RouteTarget] = {target.name: target for target in routes}
        self.min_confidence_threshold = min_confidence_threshold
        self.llm_model_name = llm_model_name
        self.llm_temperature = llm_temperature

        if default_fallback_route_name:
            if default_fallback_route_name not in self.routes:
                raise ValueError(f"Default fallback route '{default_fallback_route_name}' not found in provided routes.")
        self.default_fallback_route_name = default_fallback_route_name

        self.system_prompt = system_prompt or self._get_default_system_prompt()

    def _get_default_system_prompt(self) -> str:
        """
        Generates the default system prompt for instructing the routing LLM.
        This prompt emphasizes precision, structure, and critical evaluation.
        """
        return (
            "You are an expert routing assistant for the 'Vishustra' framework. "
            "Your critical task is to analyze a user query and select the single most appropriate "
            "target from a list of available routes. Each route has a unique name and "
            "a detailed, comprehensive description of what it handles. You must provide "
            "your decision and reasoning in a structured JSON format, adhering strictly "
            "to the specified schema. Be precise and consider the semantic meaning carefully."
        )

    def _generate_routing_prompt(self, query: str) -> List[ChatMessage]:
        """
        Constructs the messages list for the LLM, including the system prompt,
        formatted route descriptions, and the user query with output instructions.

        Args:
            query: The user's query string to be routed.

        Returns:
            A list of `ChatMessage` objects ready for the LLM provider.
        """
        route_descriptions = "\n".join([
            f"- \"{target.name}\": \"{target.description}\""
            for target in self.routes.values()
        ])

        user_prompt_content = f"""
Here is the user query that needs to be routed:
"{query}"

Here are the available routes and their detailed descriptions:
{route_descriptions}

Please provide your selection in a JSON object with the following keys.
It is critical that the JSON is perfectly valid and follows this exact structure:
- "selected_target_name": The 'name' (string) of the single best matching `RouteTarget`. If, after careful consideration, no target is confidently suitable, provide "none".
- "confidence_score": A float between 0.0 and 1.0 indicating your confidence in the selection. A score below 0.5 suggests low confidence.
- "reasoning": A brief, concise, yet informative explanation (string) of why you selected this target, or why none were suitable.
- "all_target_scores": A dictionary (JSON object) where keys are the names of ALL provided `RouteTarget`s (string) and values are your estimated confidence (float 0.0-1.0) for that specific target based on the query. Ensure all provided route names are present as keys.

Example JSON output:
{{
  "selected_target_name": "product_info_retrieval",
  "confidence_score": 0.95,
  "reasoning": "The query explicitly asks for product specifications and features, which aligns perfectly with the 'product_info_retrieval' route.",
  "all_target_scores": {{
    "customer_support_chain": 0.1,
    "product_info_retrieval": 0.95,
    "user_profile_update": 0.05,
    "general_chat": 0.25
  }}
}}

Ensure your response is valid JSON, contains all specified keys, and directly follows this format. Do not include any additional text or formatting outside the JSON object.
"""
        messages = [
            ChatMessage(role="system", content=self.system_prompt),
            ChatMessage(role="user", content=user_prompt_content)
        ]
        return messages

    async def _parse_llm_response(self, response_content: str) -> Dict[str, Any]:
        """
        Parses the JSON response from the LLM and validates its structure
        against the expected `RouteDecision` components.

        Args:
            response_content: The raw string content received from the LLM.

        Returns:
            A dictionary representing the parsed and validated LLM decision.

        Raises:
            ValueError: If the response is not valid JSON or does not conform
                        to the expected structure.
        """
        try:
            data = json.loads(response_content)
            # Basic validation of keys and types
            required_keys_types = {
                "selected_target_name": str,
                "confidence_score": (int, float),
                "reasoning": str,
                "all_target_scores": dict
            }

            for key, expected_type in required_keys_types.items():
                if key not in data:
                    raise ValueError(f"Missing required key '{key}' in LLM response.")
                if not isinstance(data[key], expected_type):
                    raise ValueError(f"Invalid type for key '{key}'. Expected {expected_type}, got {type(data[key])}.")

            # Validate confidence_score range
            if not (0.0 <= data["confidence_score"] <= 1.0):
                raise ValueError("Confidence score must be between 0.0 and 1.0.")

            # Validate scores within all_target_scores
            for target_name, score in data["all_target_scores"].items():
                if not isinstance(score, (int, float)) or not (0.0 <= score <= 1.0):
                    raise ValueError(f"Invalid score '{score}' for target '{target_name}' in 'all_target_scores'. Must be float between 0.0 and 1.0.")
                if target_name not in self.routes:
                    logger.warning(f"LLM hallucinated a target name '{target_name}' in 'all_target_scores' that is not a defined route.")

            return data
        except json.JSONDecodeError as e:
            logger.error(f"Failed to decode LLM response as JSON: {e}. Raw response: '{response_content}'")
            raise ValueError("LLM response was not valid JSON.") from e
        except ValueError as e:
            logger.error(f"LLM response JSON structure invalid: {e}. Raw response: '{response_content}'")
            raise e
        except Exception as e:
            logger.error(f"Unexpected error parsing LLM response: {e}. Raw response: '{response_content}'")
            raise e

    async def route(self, query: str, **llm_kwargs) -> RouteDecision:
        """
        Asynchronously routes a given query to the most appropriate `RouteTarget`
        based on semantic understanding by an LLM.

        The routing logic prioritizes a confident LLM selection, then
        looks for a high-scoring alternative if the LLM's primary pick was low confidence
        or 'none', and finally defaults to a fallback route if configured.

        Args:
            query: The user query or request string to be routed.
            llm_kwargs: Additional keyword arguments to pass directly to the
                        LLM provider's `async_chat_complete` method (e.g., `model`, `temperature`).

        Returns:
            A `RouteDecision` object detailing the selected target, confidence,
            reasoning, and whether a fallback was triggered. This method always
            returns a `RouteDecision`, even if it indicates no match or a forced fallback.
        """
        logger.debug(f"Attempting to route query: '{query}'")

        messages = self._generate_routing_prompt(query)
        llm_call_params = {
            "temperature": self.llm_temperature,
            **llm_kwargs
        }
        if self.llm_model_name:
            llm_call_params["model"] = self.llm_model_name

        selected_target: Optional[RouteTarget] = None
        confidence_score: float = 0.0
        reasoning: Optional[str] = None
        all_scores: Dict[str, float] = {}
        fallback_triggered: bool = False

        try:
            llm_response = await self.llm_provider.async_chat_complete(
                messages=messages,
                **llm_call_params
            )
            response_content = llm_response.message.content
            parsed_response = await self._parse_llm_response(response_content)

            llm_selected_name = parsed_response["selected_target_name"]
            llm_confidence = float(parsed_response["confidence_score"])
            llm_reasoning = parsed_response["reasoning"]
            all_scores = parsed_response["all_target_scores"]

            # Step 1: Evaluate LLM's explicit selection
            if llm_selected_name != "none" and llm_selected_name in self.routes:
                if llm_confidence >= self.min_confidence_threshold:
                    selected_target = self.routes[llm_selected_name]
                    confidence_score = llm_confidence
                    reasoning = llm_reasoning
                    logger.info(f"Router confidently selected '{selected_target.name}' (Conf: {confidence_score:.2f}) for query: '{query}'")
                else:
                    fallback_triggered = True
                    logger.warning(
                        f"LLM suggested '{llm_selected_name}' (Conf: {llm_confidence:.2f}), "
                        f"but below threshold ({self.min_confidence_threshold:.2f}). Considering fallback."
                    )
            else:
                fallback_triggered = True
                if llm_selected_name == "none":
                    logger.warning(f"LLM explicitly returned 'none' for query: '{query}'. Considering fallback.")
                else:
                    logger.warning(f"LLM returned invalid/unknown target name '{llm_selected_name}' for query: '{query}'. Considering fallback.")

            # Step 2: If no confident selection, re-evaluate based on 'all_target_scores' or use default fallback
            if selected_target is None:
                # Find the highest scored valid target from all_scores
                highest_scored_valid_target_name = None
                highest_score_from_all = 0.0

                for name, score in all_scores.items():
                    if name in self.routes and score > highest_score_from_all:
                        highest_score_from_all = score
                        highest_scored_valid_target_name = name

                if highest_scored_valid_target_name and highest_score_from_all >= self.min_confidence_threshold:
                    # A confident target found in all_scores, even if LLM's primary pick was 'none' or low conf
                    selected_target = self.routes[highest_scored_valid_target_name]
                    confidence_score = highest_score_from_all
                    reasoning = f"Re-evaluated based on highest score in 'all_target_scores': '{highest_scored_valid_target_name}' (score: {highest_score_from_all:.2f}). Original LLM reasoning: {llm_reasoning}"
                    fallback_triggered = False # We found a confident route after all
                    logger.info(f"Re-evaluation found confident route '{selected_target.name}' (Conf: {confidence_score:.2f}) for query: '{query}'")
                elif self.default_fallback_route_name:
                    # No confident route found, use the configured default fallback
                    selected_target = self.routes[self.default_fallback_route_name]
                    confidence_score = 0.0 # Indicate it's a forced fallback
                    reasoning = f"Default fallback triggered. No confident primary route found. Original LLM reasoning: {llm_reasoning}"
                    fallback_triggered = True
                    logger.warning(f"Using default fallback route '{self.default_fallback_route_name}' for query: '{query}' due to lack of confident match.")
                else:
                    # No confident route and no default fallback
                    selected_target = None
                    confidence_score = 0.0
                    reasoning = f"No confident route found and no default fallback route configured for query: '{query}'. Original LLM reasoning: {llm_reasoning}"
                    fallback_triggered = True
                    logger.error(f"CRITICAL: Semantic routing failed to find any suitable route or fallback for query: '{query}'.")

        except (ValueError, ValidationError) as e:
            # Handle parsing errors or structural validation failures from the LLM response
            logger.error(f"Error during LLM interaction or response parsing for query '{query}': {e}", exc_info=True)
            if self.default_fallback_route_name:
                selected_target = self.routes[self.default_fallback_route_name]
                confidence_score = 0.0
                reasoning = f"Critical LLM response parsing error. Triggered default fallback: {e}"
                fallback_triggered = True
                logger.warning(f"Using default fallback route '{self.default_fallback_route_name}' due to LLM response parsing error for query: '{query}'.")
            else:
                selected_target = None
                confidence_score = 0.0
                reasoning = f"Critical LLM response parsing error and no fallback configured: {e}"
                fallback_triggered = True
                logger.error(f"CRITICAL: Routing failed due to LLM response parsing error and no fallback for query: '{query}'.")
        except Exception as e:
            # Catch all other unexpected errors during the routing process
            logger.error(f"Unexpected error during semantic routing for query '{query}': {e}", exc_info=True)
            if self.default_fallback_route_name:
                selected_target = self.routes[self.default_fallback_route_name]
                confidence_score = 0.0
                reasoning = f"Unexpected error during routing. Triggered default fallback: {e}"
                fallback_triggered = True
                logger.warning(f"Using default fallback route '{self.default_fallback_route_name}' due to unexpected error for query: '{query}'.")
            else:
                selected_target = None
                confidence_score = 0.0
                reasoning = f"Unexpected routing error and no fallback configured: {e}"
                fallback_triggered = True
                logger.error(f"CRITICAL: Routing failed due to unexpected error and no fallback for query: '{query}'.")

        return RouteDecision(
            selected_target=selected_target,
            confidence_score=confidence_score,
            reasoning=reasoning,
            all_scores=all_scores,
            fallback_triggered=fallback_triggered
        )